// Loads the prototype dataset (generated by data/build_prototype_data.py from the
// H&M analysis) and exposes the read helpers the API routes use. Loaded once at
// startup and held in memory — it's ~575KB of static, read-only data.
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const data = JSON.parse(readFileSync(path.join(__dirname, "data", "prototype.json"), "utf8"));

const byId = new Map(data.products.map((p) => [p.id, p]));
const communityById = new Map(data.communities.map((c) => [c.id, c]));
const lookById = new Map(data.looks.map((l) => [l.id, l]));

export const meta = data.meta;

// Slim card shape for list views.
function card(p) {
  if (!p) return null;
  return {
    id: p.id, name: p.name, brand: p.brand, price: p.price,
    colour: p.colour, hex: p.hex, slot: p.slot, slotLabel: p.slotLabel,
    productType: p.productType, garmentGroup: p.garmentGroup,
    appearance: p.appearance, communityId: p.communityId,
    hasOutfit: data.outfits[p.id] !== undefined,
  };
}

export function listProducts({ slot, community, q, limit = 60 } = {}) {
  let items = data.products;
  if (slot) items = items.filter((p) => p.slot === slot);
  if (community != null) items = items.filter((p) => p.communityId === Number(community));
  if (q) {
    const needle = q.toLowerCase();
    items = items.filter(
      (p) => p.name.toLowerCase().includes(needle) || p.brand.toLowerCase().includes(needle) || p.colour.toLowerCase().includes(needle)
    );
  }
  return items.slice(0, Number(limit)).map(card);
}

export function getProduct(id) {
  const p = byId.get(id);
  if (!p) return null;
  return { ...p, community: p.communityId != null ? communityById.get(p.communityId) ?? null : null };
}

// The "Complete this outfit" recommendation — resolves partner ids to full cards.
export function getOutfit(id) {
  const o = data.outfits[id];
  const anchor = byId.get(id);
  if (!anchor) return null;
  if (!o) return { anchor: card(anchor), items: [], bundlePrice: anchor.price, available: false };
  const items = o.items
    .map((it) => {
      const p = byId.get(it.id);
      if (!p) return null;
      return { ...card(p), rationale: it.rationale, provenance: it.provenance, lift: it.lift };
    })
    .filter(Boolean);
  return { anchor: card(anchor), items, bundlePrice: o.bundlePrice, available: true };
}

export function listCommunities() {
  return data.communities.map((c) => ({
    id: c.id, label: c.label, shortLabel: c.shortLabel, hex: c.hex,
    modalColour: c.modalColour, modalGarment: c.modalGarment,
    distinctiveColour: c.distinctiveColour, nGarmentGroups: c.nGarmentGroups,
    size: c.size, productCount: c.productIds.length,
  }));
}

export function getCommunity(id) {
  const c = communityById.get(Number(id));
  if (!c) return null;
  return { ...c, products: c.productIds.map((pid) => card(byId.get(pid))).filter(Boolean) };
}

export function listLooks() {
  return data.looks.map((l) => ({ ...l, anchor: card(byId.get(l.anchorId)) }));
}

export function getLook(id) {
  const l = lookById.get(id);
  if (!l) return null;
  const outfit = getOutfit(l.anchorId);
  return { ...l, anchor: outfit?.anchor ?? null, items: outfit?.items ?? [], bundlePrice: outfit?.bundlePrice };
}
